#!/usr/bin/env python3
"""Convert a document.cookie string to Netscape-format cookies.txt for Zhihu.

Usage:
    python scripts/convert_cookies.py --input cookies_raw.txt
    ZHIHU_COOKIES="k=v; k2=v2" python scripts/convert_cookies.py
    python scripts/convert_cookies.py < cookies_raw.txt

The cookie string is read from (in priority order):
  1. --input <path>   a file containing the document.cookie string
  2. ZHIHU_COOKIES    environment variable
  3. stdin

Credentials are NEVER hardcoded in this file. If you previously relied on the
baked-in string, note that those cookies were committed to git history and must
be considered leaked — rotate the Zhihu session and update the
ZHIHU_COOKIES_B64 repo secret.
"""
import argparse
import os
import sys
from pathlib import Path

OUTPUT_PATH = Path("_snapshots/zhihu_cookies.txt")


def read_cookie_string(args):
    if args.input:
        return Path(args.input).read_text(encoding="utf-8").strip()
    env = os.environ.get("ZHIHU_COOKIES")
    if env:
        return env.strip()
    if not sys.stdin.isatty():
        data = sys.stdin.read().strip()
        if data:
            return data
    return None


def main():
    parser = argparse.ArgumentParser(
        description="Convert a document.cookie string to Netscape cookies.txt for Zhihu.")
    parser.add_argument("--input", help="Path to a file containing the document.cookie string")
    parser.add_argument("--output", default=str(OUTPUT_PATH), help="Output cookies.txt path")
    args = parser.parse_args()

    cookie_string = read_cookie_string(args)
    if not cookie_string:
        print("Error: no cookie string provided. Use --input <path>, set the ZHIHU_COOKIES env "
              "var, or pipe the string via stdin.", file=sys.stderr)
        sys.exit(1)

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    expiry = 1893456000  # 2030-01-01
    domain = ".zhihu.com"
    path = "/"

    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/docs/http-cookies.html",
        "# This file was auto-generated by convert_cookies.py",
        f"# Generated for zhihu.com at {expiry}",
    ]

    for part in cookie_string.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, _, value = part.partition("=")
        name, value = name.strip(), value.strip()
        # Netscape format: domain TAB flag TAB path TAB secure TAB expiry TAB name TAB value
        lines.append(f"{domain}\tTRUE\t{path}\tFALSE\t{expiry}\t{name}\t{value}")

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Saved {len(lines) - 4} cookies to {output}")
    print("Done! Run 'python scripts/zhihu_cookies.py' to verify.")


if __name__ == "__main__":
    main()
