#!/usr/bin/env python3
"""Convert a document.cookie string to Netscape-format cookies.txt for Zhihu.

Usage:
    python scripts/convert_cookies.py
"""
from pathlib import Path

COOKIE_STRING = (
    "_xsrf=zTYABmUq4Vl4v6wDbu2UaR06OwPFXW6y; "
    "_zap=509a4f3b-6c6a-4ec4-8b56-8ab1ced5383a; "
    "d_c0=OKPTBJiKpBqPTr93GEMvKjZFGOiT_Jb9uV8=|1750498784; "
    "__snaker__id=bLR0TJ2oP2rF5D1X; "
    "q_c1=68022e1c754a47b981412bc576987432|1750906318000|1750906318000; "
    "edu_user_uuid=edu-v1|a96a76a9-c6bf-400d-ac26-a0c11f86b8d9; "
    "HMACCOUNT=19B682D08EFD08B7; "
    "Hm_lvt_98beee57fd2ef70ccdd5ca52b9740c49=1778315364; "
    "__zse_ck=005_h6g/4zcCrhU8OCYziPjlg67HTeIl91qz=nirxexDAmn1kbKJAchD8FS2ZE8wh3Df1nRYStjlFdimB/cO9TO5OeDLecxxs=yr=87J1eZsHUjL3N7/k1jYW3y9kD7EPq3I-txn2X8YLM7r13hZI36oddRO4awRDfnFYowu2ytuLLg3SK2kNkvki+4wu01iiOdk4JbeqzE9DCK67RvutUpjwUEreWbTrOmYoRBhcG8qM4v7cx1x3WTB5HrM9nApOaSIN; "
    "SESSIONID=5q2dLzuGbQdXqfR6M6OaQ9vWYClmhs7YOS3FGvC1B69; "
    "JOID=Wl8RCkNofJTwJM5VKyPly9KxRf49Ug6rlWi7I2EKIvOlVKgIHpOUjpsrwlsnfdBpCMTFctnaNQGfvk1SbPUY3GE=; "
    "osd=W1kTA0ppepb5Lc9TKSrsytSzTPc8VAyinGm9IWgDI_WnXaEJGJGdh5otwFIufNZrAc3EdNvTPACZvERbbfMa1Wg=; "
    "BEC=4589376d83fd47c9203681b16177ae43; "
    "Hm_lpvt_98beee57fd2ef70ccdd5ca52b9740c49=1779950561"
)

OUTPUT_PATH = Path("_snapshots/zhihu_cookies.txt")


def main():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    expiry = 1893456000  # 2030-01-01
    domain = ".zhihu.com"
    path = "/"

    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/docs/http-cookies.html",
        "# This file was auto-generated by convert_cookies.py",
        f"# Generated for zhihu.com at {expiry}",
    ]

    for part in COOKIE_STRING.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, _, value = part.partition("=")
        name, value = name.strip(), value.strip()

        # Netscape format: domain TAB flag TAB path TAB secure TAB expiry TAB name TAB value
        lines.append(f"{domain}\tTRUE\t{path}\tFALSE\t{expiry}\t{name}\t{value}")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Saved {len(lines) - 4} cookies to {OUTPUT_PATH}")
    print("Done! Run 'python scripts/zhihu_cookies.py' to verify.")


if __name__ == "__main__":
    main()
