#!/usr/bin/env python3
"""Convert a browser Cookie header / document.cookie string to Netscape cookies.txt + base64.

No browser extension required. Paste the Cookie string from DevTools
(Network → request → Request Headers → Cookie).

Usage:
    python scripts/cookie_string_to_b64.py --test
    python scripts/cookie_string_to_b64.py --input cookies_raw.txt --test
    python scripts/cookie_string_to_b64.py "SESSIONID=...; _zap=..."

Output:
    _snapshots/zhihu_cookies.txt   (for local monitor.py)
    zhihu_cookies.b64.txt          (paste into GitHub Secret ZHIHU_COOKIES_B64)

Credentials are never hardcoded in this file.
"""
from __future__ import annotations

import argparse
import base64
import os
import sys
from http.cookiejar import MozillaCookieJar
from pathlib import Path

import requests

BASE_DIR = Path(__file__).resolve().parent.parent
COOKIE_PATH = BASE_DIR / "_snapshots" / "zhihu_cookies.txt"
B64_PATH = BASE_DIR / "zhihu_cookies.b64.txt"

REQUEST_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    "Referer": "https://www.zhihu.com/",
}

TEST_USERS = [
    ("卡里奇 - 知乎", "lyq2002"),
    ("堪村无业土博鼠 - 知乎", "allen-zhu-16"),
    ("傅宇千", "zxhy-1999"),
]


def read_cookie_string(args: argparse.Namespace) -> str:
    if args.cookie_string:
        return args.cookie_string.strip()
    if args.input:
        return Path(args.input).read_text(encoding="utf-8").strip()
    env = os.environ.get("ZHIHU_COOKIES")
    if env:
        return env.strip()
    if not sys.stdin.isatty():
        data = sys.stdin.read().strip()
        if data:
            return data
    return ""


def normalize_cookie_string(raw: str) -> str:
    s = raw.strip()
    if (s.startswith("'") and s.endswith("'")) or (s.startswith('"') and s.endswith('"')):
        s = s[1:-1].strip()
    return s


def parse_cookie_pairs(cookie_string: str) -> dict[str, str]:
    """Parse 'a=1; b=2' — duplicate names keep the last value (browser-like)."""
    pairs: dict[str, str] = {}
    for part in cookie_string.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, _, value = part.partition("=")
        name, value = name.strip(), value.strip()
        if name:
            pairs[name] = value
    return pairs


def to_netscape_lines(pairs: dict[str, str], expiry: int = 1893456000) -> list[str]:
    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/docs/http-cookies.html",
        "# Generated by cookie_string_to_b64.py",
    ]
    for name, value in pairs.items():
        lines.append(f".zhihu.com\tTRUE\t/\tFALSE\t{expiry}\t{name}\t{value}")
    return lines


def write_cookies(pairs: dict[str, str], output: Path = COOKIE_PATH) -> int:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = to_netscape_lines(pairs)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(pairs)


def to_base64(cookie_file: Path = COOKIE_PATH) -> str:
    return base64.b64encode(cookie_file.read_bytes()).decode("ascii")


def test_session(cookie_file: Path = COOKIE_PATH) -> bool:
    session = requests.Session()
    session.headers.update(REQUEST_HEADERS)
    jar = MozillaCookieJar(cookie_file)
    jar.load(ignore_discard=True, ignore_expires=True)
    session.cookies.update(jar)

    ok = True
    for label, zid in TEST_USERS:
        url = f"https://www.zhihu.com/api/v4/members/{zid}/answers?limit=1&order_by=created"
        try:
            r = session.get(url, timeout=15)
            if r.status_code == 200:
                print(f"  [OK] {label} ({zid})")
            else:
                print(f"  [FAIL] {label} ({zid}): HTTP {r.status_code}")
                ok = False
        except Exception as e:
            print(f"  [FAIL] {label} ({zid}): {e}")
            ok = False
    return ok


def main():
    parser = argparse.ArgumentParser(
        description="Convert Cookie header string → Netscape cookies.txt + ZHIHU_COOKIES_B64")
    parser.add_argument("cookie_string", nargs="?", help="Cookie string (or use --input / ZHIHU_COOKIES)")
    parser.add_argument("--input", help="File containing the cookie string")
    parser.add_argument("--output", default=str(COOKIE_PATH), help="Netscape cookies output path")
    parser.add_argument("--b64-out", default=str(B64_PATH), help="Base64 output file path")
    parser.add_argument("--test", action="store_true", help="Test Zhihu API for monitored users")
    parser.add_argument("--quiet", action="store_true", help="Only print base64 to stdout")
    args = parser.parse_args()

    raw = read_cookie_string(args)
    if not raw:
        print("Error: provide cookie string via argument, --input, ZHIHU_COOKIES, or stdin.",
              file=sys.stderr)
        sys.exit(1)

    pairs = parse_cookie_pairs(normalize_cookie_string(raw))
    if not pairs:
        print("Error: no valid name=value pairs found.", file=sys.stderr)
        sys.exit(1)

    if "z_c0" not in pairs and not args.quiet:
        print("Warning: 'z_c0' cookie missing — Zhihu API often requires it.", file=sys.stderr)
        print("  Re-copy the full Cookie header from DevTools while logged in on zhihu.com.",
              file=sys.stderr)

    output = Path(args.output)
    count = write_cookies(pairs, output)
    b64 = to_base64(output)
    Path(args.b64_out).write_text(b64 + "\n", encoding="utf-8")

    if args.quiet:
        print(b64)
    else:
        print(f"Wrote {count} cookies → {output}")
        print(f"Wrote base64 ({len(b64)} chars) → {args.b64_out}")
        print("\nGitHub Secret ZHIHU_COOKIES_B64:")
        print("  Settings → Secrets → Actions → New repository secret")
        print("  Name: ZHIHU_COOKIES_B64")
        print(f"  Value: contents of {args.b64_out} (one line)")

    if args.test:
        print("\nTesting Zhihu API …")
        if test_session(output):
            print("\nAll tests passed.")
        else:
            print("\nSome tests failed — cookies may be expired or incomplete.", file=sys.stderr)
            sys.exit(2)

    if not args.quiet and not args.test:
        print("\nTip: run with --test to verify before uploading the secret.")


if __name__ == "__main__":
    main()
